/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/models/harley/scene.gltf --types 
Author: everhard (https://sketchfab.com/everhard)
License: SKETCHFAB Editorial (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/harley-davidson-vrscdx-night-rod-special-9b57af9e68704f7ebe044a1acb02fae2
Title: Harley-Davidson VRSCDX Night Rod Special
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    bikebelt: THREE.MeshStandardMaterial
    bikebelt__env_1: THREE.MeshStandardMaterial
    black1__env_1_spec: THREE.MeshStandardMaterial
    black1__env_2_spec: THREE.MeshStandardMaterial
    black1__env_3_spec: THREE.MeshStandardMaterial
    black1__env_4_spec: THREE.MeshStandardMaterial
    black1__env_6_spec: THREE.MeshStandardMaterial
    black1__env_7_spec: THREE.MeshStandardMaterial
    black1__spec: THREE.MeshStandardMaterial
    black_1: THREE.MeshStandardMaterial
    bron__env_16_spec: THREE.MeshStandardMaterial
    bron__env_17_spec: THREE.MeshStandardMaterial
    bron__env_26_spec: THREE.MeshStandardMaterial
    bron__env_6_spec: THREE.MeshStandardMaterial
    carpback: THREE.MeshStandardMaterial
    carplate: THREE.MeshStandardMaterial
    chrome2__env_2_trans: THREE.MeshStandardMaterial
    chrome2__env_6_trans: THREE.MeshStandardMaterial
    diavel_disk__env_12_spec: THREE.MeshStandardMaterial
    dmetal__env_2: THREE.MeshStandardMaterial
    dmetal__env_3: THREE.MeshStandardMaterial
    dyna_details2__spec: THREE.MeshStandardMaterial
    dyna_mat1: THREE.MeshStandardMaterial
    dyna_mat1__env_1: THREE.MeshStandardMaterial
    hdunlop: THREE.MeshStandardMaterial
    htire2: THREE.MeshStandardMaterial
    iron883main: THREE.MeshStandardMaterial
    med__env_1: THREE.MeshStandardMaterial
    med__env_7_spec_trans: THREE.MeshStandardMaterial
    metalgrill__env_1: THREE.MeshStandardMaterial
    mirorglass__env_50_spec: THREE.MeshStandardMaterial
    otrajenie: THREE.MeshStandardMaterial
    reflector_red__env_3: THREE.MeshStandardMaterial
    reflector_yel__env_3: THREE.MeshStandardMaterial
    roof: THREE.MeshStandardMaterial
    supdot: THREE.MeshStandardMaterial
    uni_piramid_ao: THREE.MeshStandardMaterial
    vehiclelights128__FR: THREE.MeshStandardMaterial
    vehiclelights128__RR: THREE.MeshStandardMaterial
    vehiclelights__FR: THREE.MeshStandardMaterial
    vrod_metal: THREE.MeshStandardMaterial
    vrod_metal__env_1: THREE.MeshStandardMaterial
    vrod_metal__env_2_spec: THREE.MeshStandardMaterial
    vrod_speedo: THREE.MeshStandardMaterial
    vrodparts: THREE.MeshStandardMaterial
    vrodparts__env_2: THREE.MeshStandardMaterial
    vrodrim__env_1: THREE.MeshStandardMaterial
    vrodrim__env_2: THREE.MeshStandardMaterial
    vrodstripe__env_1: THREE.MeshStandardMaterial
    vrodstripe__env_2: THREE.MeshStandardMaterial
    white1: THREE.MeshStandardMaterial
    white1__env_1: THREE.MeshStandardMaterial
    white__env_1: THREE.MeshStandardMaterial
    white__prim_env_6_spec: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Harley(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/harley/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.bikebelt} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.bikebelt__env_1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.black1__env_1_spec} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.black1__env_2_spec} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.black1__env_3_spec} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.black1__env_4_spec} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.black1__env_6_spec} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.black1__env_7_spec} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.black1__spec} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.black_1} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.bron__env_16_spec} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.bron__env_17_spec} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.bron__env_26_spec} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.bron__env_6_spec} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.carpback} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.carplate} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.chrome2__env_2_trans} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.chrome2__env_6_trans} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.diavel_disk__env_12_spec} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.dmetal__env_2} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.dmetal__env_3} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.dyna_details2__spec} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.dyna_mat1} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.dyna_mat1__env_1} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.hdunlop} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.htire2} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.iron883main} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.med__env_1} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.med__env_7_spec_trans} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.metalgrill__env_1} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.mirorglass__env_50_spec} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.otrajenie} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.reflector_red__env_3} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.reflector_yel__env_3} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.roof} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.supdot} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.uni_piramid_ao} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.vehiclelights128__FR} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.vehiclelights128__RR} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.vehiclelights__FR} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.vrod_metal} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.vrod_metal__env_1} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.vrod_metal__env_2_spec} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.vrod_speedo} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.vrodparts} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.vrodparts__env_2} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.vrodrim__env_1} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.vrodrim__env_2} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.vrodstripe__env_1} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.vrodstripe__env_2} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.white1} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.white1__env_1} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.white__env_1} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.white__prim_env_6_spec} />
      </group>
    </group>
  )
}

export default Harley

useGLTF.preload('models/harley/scene.gltf')
